import Head from "next/head";
import hero from "@styles/modules/hero-section.module.scss";
import { Header } from "./home-sections/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Alon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <Header/>
          <section className={hero.container}>
            <div className={hero.bgImage}>
            <div className={hero.overlay}></div>
            </div>
          </section>
        </main>
    </>
  );
}
