import Head from "next/head";
import styles from "@/styles/modules/home.module.scss";
import header from "@/styles/modules/header.module.scss"
import { HeaderIcon } from "@/components/header-icon";
import { UserHeader } from "@/components/header-user";


export default function Home() {
  return (
    <>
      <Head>
        <title>Alon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <header className={header.blackHeader}>
              <div className={header.container}>
                <HeaderIcon variant="black"/>
                <UserHeader variant="black"/>
              </div>
          </header>
        </main>
    </>
  );
}
